sonar.projectKey=GVI-TP
sonar.projectName=GVI-TP
sonar.sources=.
sonar.language=py
sonar.python.version=3
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,tests/**
sonar.host.url=http://localhost:9000