sonar.projectKey=GVI-TP
sonar.projectName=GVI-TP
sonar.sources=.
sonar.language=py
sonar.python.version=3
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,tests/**
sonar.host.url=http://localhost:9000
sonar.token=squ_8c7407792675a5272eab79625d37081c891b1510 # To be updated